blog/urls.py
from django.urls import path
from . import views #imports blog app views.py bc they are in same folder u can use.

app_name = 'blog' #now when u want to reference any url from here you have to specify "blog:x"

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings #gets info from settings file
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')), #paths to all urlpatterns contained in blogs.urls
]
#adding an additional path
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=250)
    date = models.DateField()
 
    def __str__(self): #makes title appear in admin database
        return self.title

portfolio/models.py
from django.db import models
from django.db.models.fields import URLField

# Create your models here.
#inherits from django models class
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True) #by default blank=False, being true allows it to be blank

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog #import stuff from database, so i can send it to template


def all_blogs(request):
    blogs = Blog.objects.order_by('-date') #grabs all objects from the database that are Blog objects (in models file), turns them into python objects
    return render(request, 'blog/all_blogs.html', {'blogs':blogs}) #puts all Blog objects into a list

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})#whats in soft brackets is being passed forward

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all() #grabs all objects from the database that are Project objects (in models file), turns them into python objects
    return render(request, 'portfolio/home.html', {'projects':projects}) #puts all Project objects into a list

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}
<h1>Will's blogs</h1>

<!-- only plural if there are many blogs-->
<h2>Nick has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h2> 

<!-- django template for loop syntax-->
{% for blog in blogs %}

<a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a> 
<h5>{{ blog.date }}</h5>
<p>{{ blog.description }}</p> <!-- description|truncatechars:100 will limit characters in description-->

{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}

    <h1>{{ blog.title }}</h1>

    <h2>{{ blog.date }}</h2>

    <p>{{ blog.description}}</p>

{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/Logo.png" %}">

  <title>William Sheehan</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/logo.jpeg" %}" width="30" height="30" class="d-inline-block align-top" alt="Nick's Logo">
        <span>Will Sheehan</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/resume.png" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/will-sheehan-810149202/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/ZappyCode" target="_blank">Twitter</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %} <!--name 'content' must match that of base file-->
    <h1>Will's Portfolio of Programs</h1>

    <br>

    {% load static %} <!--allows for access to image contained in static folder-->
    <img src="{% static 'portfolio/dinertablephoto.JPEG' %}", height=400, wdth=400 class = center>

    <!--  <a href="{% url 'blog:all_blogs' %}">Blog</a> -->
    <!-- <a href="{% static 'portfolio/resume.png' %}">Resume</a> -->
    <br>
    <br>
    <br>

    <div class="row justify-content-center">
        <!-- django template for loop syntax-->
        {% for project in projects %}
        <div class="col-sm-12 col-lg-4">

            {% if project.url %}
            <a href="{{ project.url }}">
                <img src="{{ project.image.url }}" class="img-fluid mb-2">
            </a>
            {% else %}

            <img src="{{ project.image.url }}" class="img-fluid mb-2">
            {% endif %}
            <h3>{{ project.title }}</h3>
            <p>{{ project.description }}</p>

        </div>
        {% endfor %}
    </div>

{% endblock %}